name: Terraform CI

on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
    paths:
      - terraform/**
  pull_request:
    branches:
      - main
    paths:
      - terraform/**

jobs:
  execute-terraform-plan:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - name: Authenticate with Azure
        uses: azure/login@v2.1.1
        with:
          creds: ${{ secrets.ARM_CREDENTIALS }}
      - name: Setup Terraform and Terragrunt
        run: |
          tf_version="${{ env.TERRAFORM_VERSION }}"
          tg_version="${{ env.TERRAGRUNT_VERSION }}"

          curl -Lo terraform.zip https://releases.hashicorp.com/terraform/${tf_version}/terraform_${tf_version}_linux_amd64.zip
          unzip terraform.zip -d /usr/local/bin/
          curl -Lo /usr/local/bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/${tg_version}/terragrunt_linux_amd64

  execute-terraform-apply:
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Authenticate with Azure
        uses: azure/login@v2.1.1
        with:
          creds: ${{ secrets.ARM_CREDENTIALS }}
      - name: Setup Terraform and Terragrunt
        run: |
          tf_version="${{ env.TERRAFORM_VERSION }}"
          tg_version="${{ env.TERRAGRUNT_VERSION }}"

          curl -Lo terraform.zip https://releases.hashicorp.com/terraform/${tf_version}/terraform_${tf_version}_linux_amd64.zip
          unzip terraform.zip -d /usr/local/bin/
          curl -Lo /usr/local/bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/${tg_version}/terragrunt_linux_amd64
